# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f07202d7edd9a538308ff0da22d85186"
name = "ParserVo"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locations,read_metaobject_definitions,read_metaobjects,read_products,write_inventory,write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
