import type { ActionFunctionArgs, LoaderFunctionArgs } from "react-router";
import { Form, useActionData, useLoaderData, useNavigation } from "react-router";
import { authenticate } from "../shopify.server";
import db from "../db.server";

const defaults=[{name:"Stone Island Poland Sale",code:"stone-island-pl-sale",catalogUrl:"https://www.stoneisland.com/en-pl/men/sales/view-all-sales",currency:"PLN"},{name:"Vitkac",code:"vitkac",catalogUrl:"https://www.vitkac.com/",currency:"PLN"}];
export async function loader({request}:LoaderFunctionArgs){const {session}=await authenticate.admin(request);let sources=await db.supplierSource.findMany({where:{shop:session.shop},orderBy:{createdAt:'asc'}});if(!sources.length){await db.supplierSource.createMany({data:defaults.map(x=>({...x,shop:session.shop,parserMode:'browser_capture'}))});sources=await db.supplierSource.findMany({where:{shop:session.shop},orderBy:{createdAt:'asc'}});}return {sources};}
export async function action({request}:ActionFunctionArgs){const {session}=await authenticate.admin(request);const f=await request.formData();const intent=String(f.get('intent')||'save');if(intent==='add'){await db.supplierSource.create({data:{shop:session.shop,name:'New source',code:`source-${Date.now()}`,catalogUrl:'https://',currency:'PLN'}});return {ok:true,message:'Источник добавлен.'};}const id=String(f.get('id')||'');await db.supplierSource.update({where:{id},data:{name:String(f.get('name')||''),catalogUrl:String(f.get('catalogUrl')||''),productUrlPattern:String(f.get('productUrlPattern')||'')||null,currency:String(f.get('currency')||'PLN'),enabled:f.get('enabled')==='on',parserMode:String(f.get('parserMode')||'browser_capture'),defaultMarkupPercent:Number(f.get('defaultMarkupPercent')||0)||null,defaultQuantity:Number(f.get('defaultQuantity')||5),autoImport:f.get('autoImport')==='on',updateExisting:f.get('updateExisting')==='on',hideUnavailable:f.get('hideUnavailable')==='on',notes:String(f.get('notes')||'')||null}});return {ok:true,message:'Настройки источника сохранены.'};}
export default function Sources(){const {sources}=useLoaderData<typeof loader>();const a=useActionData<typeof action>();const n=useNavigation();return <main className="app-page"><header className="app-header"><div><h1 className="app-title">Sources</h1><p className="app-subtitle">Ссылки каталогов и правила каждого поставщика меняются здесь — без кода и .env.</p></div><Form method="post"><input type="hidden" name="intent" value="add"/><button className="btn btn-primary">Add source</button></Form></header>{a?.message?<div className="notice notice-success">{a.message}</div>:null}<div className="form-stack">{sources.map((s: any)=><Form method="post" className="card" key={s.id}><input type="hidden" name="id" value={s.id}/><div className="app-header"><div><h2 className="card-title">{s.name}</h2><p className="muted small">{s.code}</p></div><label className="checkbox-row"><input name="enabled" type="checkbox" defaultChecked={s.enabled}/> Enabled</label></div><div className="form-grid"><div><label>Name</label><input name="name" defaultValue={s.name}/></div><div><label>Catalog URL</label><input name="catalogUrl" defaultValue={s.catalogUrl}/></div><div><label>Product URL pattern (optional)</label><input name="productUrlPattern" defaultValue={s.productUrlPattern||''} placeholder="/product/ or regular-fit-t-shirt"/></div><div><label>Currency</label><select name="currency" defaultValue={s.currency}><option>PLN</option><option>EUR</option><option>GBP</option><option>USD</option></select></div><div><label>Parser mode</label><select name="parserMode" defaultValue={s.parserMode}><option value="browser_capture">Browser capture</option><option value="server">Server / Playwright</option><option value="manual_html">Manual HTML</option></select></div><div><label>Quantity</label><input type="number" name="defaultQuantity" defaultValue={s.defaultQuantity}/></div><div><label>Markup override %</label><input name="defaultMarkupPercent" defaultValue={s.defaultMarkupPercent??''} placeholder="Use global"/></div></div><div className="form-grid" style={{marginTop:12}}><label className="checkbox-row"><input name="autoImport" type="checkbox" defaultChecked={s.autoImport}/> Auto import</label><label className="checkbox-row"><input name="updateExisting" type="checkbox" defaultChecked={s.updateExisting}/> Update existing</label><label className="checkbox-row"><input name="hideUnavailable" type="checkbox" defaultChecked={s.hideUnavailable}/> Hide unavailable</label></div><div style={{marginTop:12}}><label>Notes</label><textarea name="notes" rows={2} defaultValue={s.notes||''}/></div><button className="btn btn-primary" style={{marginTop:12}} disabled={n.state!=='idle'}>Save source</button></Form>)}</div></main>}
